server:
  port: 5000

spring:
  application:
    name: ShortURLGenerator
  profiles:
    active: dev

logging:
  level:
    org.springframework: ERROR
    com.app.neueda: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
